export const GBIF_TAXON_KEY = 797
export const INAT_TAXON_ID = 47157

export const SPECIES_META = {
  // ─── Milkweed butterflies (Danaidae) ─────────────────────────────────────
  5130082: { common: 'Monarch', scientific: 'Danaus plexippus', color: '#5a3e28', emoji: '🦋', wingspanMm: 102, fact: 'Migrates up to 4,500 km from Canada to Mexican mountain forests — navigating by the sun and Earth\'s magnetic field.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/227923335/medium.jpeg' },
  5130090: { common: 'Queen', scientific: 'Danaus gilippus', color: '#5a3e28', emoji: '🦋', wingspanMm: 78, fact: 'The Monarch\'s southern cousin — males use hair pencils to transfer scent to females during courtship.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/163708904/medium.jpeg' },
  5130088: { common: 'Plain Tiger', scientific: 'Danaus chrysippus', color: '#5a3e28', emoji: '🦋', wingspanMm: 75, fact: 'One of the most widespread butterflies on Earth — its bitter toxins, absorbed from milkweed, deter most predators.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/58977135/medium.jpg' },

  // ─── Swallowtails (Papilionidae) ─────────────────────────────────────────
  5119785: { common: 'Eastern Tiger Swallowtail', scientific: 'Papilio glaucus', color: '#5a3e28', emoji: '🦋', wingspanMm: 140, fact: 'Females can mimic the toxic Pipevine Swallowtail in a dark morph — a striking example of Batesian mimicry.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/147896974/medium.jpg' },
  5119887: { common: 'Giant Swallowtail', scientific: 'Papilio cresphontes', color: '#5a3e28', emoji: '🦋', wingspanMm: 160, fact: 'The largest butterfly in North America — its caterpillar masquerades as a fresh bird dropping.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/83941810/medium.jpg' },
  5119800: { common: 'Old World Swallowtail', scientific: 'Papilio machaon', color: '#5a3e28', emoji: '🦋', wingspanMm: 88, fact: 'One of the most widely distributed swallowtails — found from Arctic tundra to the Sahara desert margins.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/84864834/medium.jpg' },
  5119907: { common: 'Pipevine Swallowtail', scientific: 'Battus philenor', color: '#5a3e28', emoji: '🦋', wingspanMm: 100, fact: 'Feeding on pipevine plants makes adults toxic to birds — at least five other species mimic their iridescent blue wings.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/25875295/medium.jpg' },
  5120067: { common: 'Zebra Swallowtail', scientific: 'Eurytides marcellus', color: '#5a3e28', emoji: '🦋', wingspanMm: 88, fact: 'Completely dependent on pawpaw trees — the only plants its caterpillars can eat.', photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Eurytides_marcellus_1.jpg/640px-Eurytides_marcellus_1.jpg' },
  1890955: { common: 'Black Swallowtail', scientific: 'Papilio polyxenes', color: '#5a3e28', emoji: '🦋', wingspanMm: 95, fact: 'Its caterpillar feeds on parsley and dill — a common and welcome guest in herb gardens.', photoUrl: 'https://static.inaturalist.org/photos/71573494/medium.jpeg' },

  // ─── Whites and Sulphurs (Pieridae) ──────────────────────────────────────
  5118914: { common: 'Cabbage White', scientific: 'Pieris rapae', color: '#5a3e28', emoji: '🦋', wingspanMm: 52, fact: 'Accidentally introduced to North America in the 1860s — now one of the most abundant butterflies on Earth.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/28420401/medium.jpg' },
  5118870: { common: 'Clouded Sulphur', scientific: 'Colias philodice', color: '#5a3e28', emoji: '🦋', wingspanMm: 55, fact: 'A master of thermoregulation — it angles its wings like a solar panel to warm up on cool mornings.', photoUrl: 'https://static.inaturalist.org/photos/14482181/medium.jpg' },
  5118875: { common: 'Orange Sulphur', scientific: 'Colias eurytheme', color: '#5a3e28', emoji: '🦋', wingspanMm: 60, fact: 'Reflects ultraviolet light invisible to humans — males choose mates partly by UV pattern.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/56077297/medium.jpg' },

  // ─── Gossamer-wings (Lycaenidae) ─────────────────────────────────────────
  5129378: { common: 'American Copper', scientific: 'Lycaena phlaeas', color: '#5a3e28', emoji: '🦋', wingspanMm: 30, fact: 'Males are ferociously territorial — they will chase away butterflies ten times their size from sunlit perches.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/9450/medium.jpg' },
  5134434: { common: 'Eastern Tailed-Blue', scientific: 'Cupido comyntas', color: '#5a3e28', emoji: '🦋', wingspanMm: 24, fact: 'One of the smallest butterflies in North America — barely wider than a thumbnail but with strikingly vivid blue wings.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/91562330/medium.jpeg' },
  5131256: { common: 'Holly Blue', scientific: 'Celastrina argiolus', color: '#5a3e28', emoji: '🦋', wingspanMm: 34, fact: 'Alternates host plants by season — holly in spring, ivy in summer — driven by parasitoid wasp pressure.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/394887496/medium.jpg' },
  1898286: { common: 'Karner Blue', scientific: 'Plebejus samuelis', color: '#e06868', emoji: '🦋', wingspanMm: 28, fact: 'Federally endangered — depends entirely on wild lupine, a plant of vanishing oak-savanna habitats.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/9829135/medium.jpeg' },

  // ─── Nymphalids / Brushfoots ──────────────────────────────────────────────
  5130132: { common: 'Painted Lady', scientific: 'Vanessa cardui', color: '#5a3e28', emoji: '🦋', wingspanMm: 65, fact: 'The most widely distributed butterfly on Earth — found on every continent except Antarctica and South America.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/9506438/medium.jpg' },
  5130194: { common: 'Red Admiral', scientific: 'Vanessa atalanta', color: '#5a3e28', emoji: '🦋', wingspanMm: 64, fact: 'Feeds on fermenting fruit in autumn and becomes visibly intoxicated — one of the few butterflies known to get drunk.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/53928483/medium.jpg' },
  5130344: { common: 'Mourning Cloak', scientific: 'Nymphalis antiopa', color: '#5a3e28', emoji: '🦋', wingspanMm: 80, fact: 'One of the longest-lived butterflies — adults overwinter in tree cavities and can survive nearly a year.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/11607/medium.jpg' },
  5130392: { common: 'Common Buckeye', scientific: 'Junonia coenia', color: '#5a3e28', emoji: '🦋', wingspanMm: 65, fact: 'Its dramatic eyespots serve as startle displays — up close, they can momentarily confuse a would-be predator.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/30041591/medium.jpg' },
  5130554: { common: 'Pearl Crescent', scientific: 'Phyciodes tharos', color: '#5a3e28', emoji: '🦋', wingspanMm: 32, fact: 'One of the most common butterflies in eastern North America — males patrol territories from low perches all day.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/361793/medium.jpg' },
  5130416: { common: 'Question Mark', scientific: 'Polygonia interrogationis', color: '#5a3e28', emoji: '🦋', wingspanMm: 64, fact: 'Named for a tiny silver question-mark on its hindwing underside — perfectly camouflaged as a dead leaf when closed.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/30873124/medium.jpg' },
  5130400: { common: 'Comma', scientific: 'Polygonia c-album', color: '#5a3e28', emoji: '🦋', wingspanMm: 50, fact: 'Its deeply jagged wing edges and mottled underside make it one of the most convincing dead-leaf mimics in Europe.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/155133827/medium.jpeg' },
  5130467: { common: 'Baltimore Checkerspot', scientific: 'Euphydryas phaeton', color: '#d87060', emoji: '🦋', wingspanMm: 55, fact: 'Maryland\'s state insect — dependent on turtleheads in wet meadows, a habitat shrinking rapidly across its range.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/80014247/medium.jpeg' },
  5130520: { common: 'Great Spangled Fritillary', scientific: 'Speyeria cybele', color: '#5a3e28', emoji: '🦋', wingspanMm: 85, fact: 'Only females overwinter as freshly-hatched larvae — they don\'t eat until violets emerge the following spring.', photoUrl: 'https://static.inaturalist.org/photos/568004998/medium.jpg' },
  5130258: { common: 'Viceroy', scientific: 'Limenitis archippus', color: '#5a3e28', emoji: '🦋', wingspanMm: 75, fact: 'Long thought to mimic Monarchs for protection — turns out Viceroys are also toxic and the mimicry is mutual.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/2058543/medium.jpg' },
  5130253: { common: 'White Admiral', scientific: 'Limenitis camilla', color: '#5a3e28', emoji: '🦋', wingspanMm: 60, fact: 'Glides effortlessly on motionless wings for long distances — its distinctive white band is visible from far away.', photoUrl: 'https://static.inaturalist.org/photos/593619486/medium.jpg' },
  5130315: { common: 'Small Tortoiseshell', scientific: 'Aglais urticae', color: '#5a3e28', emoji: '🦋', wingspanMm: 52, fact: 'One of Europe\'s most beloved garden butterflies — has declined sharply in some regions due to a parasitic fly.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/257869609/medium.jpg' },
  5130348: { common: 'European Peacock', scientific: 'Aglais io', color: '#5a3e28', emoji: '🦋', wingspanMm: 65, fact: 'Produces a loud hissing sound by rubbing its wings together — startling predators with a combination of sight and sound.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/4710619/medium.jpg' },

  // ─── Skippers (Hesperiidae) ───────────────────────────────────────────────
  5128855: { common: 'Silver-spotted Skipper', scientific: 'Epargyreus clarus', color: '#5a3e28', emoji: '🦋', wingspanMm: 54, fact: 'The most recognizable skipper in North America — its caterpillar stitches leaves into a shelter, sleeping inside by day.', photoUrl: 'https://static.inaturalist.org/photos/60570/medium.jpg' },
  5128925: { common: 'Fiery Skipper', scientific: 'Hylephila phyleus', color: '#5a3e28', emoji: '🦋', wingspanMm: 30, fact: 'A frequent lawn visitor that thrives in disturbed urban environments — one of the most adaptable skippers.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/2611412/medium.jpg' },

  // ─── Moths ───────────────────────────────────────────────────────────────
  1810488: { common: 'Luna Moth', scientific: 'Actias luna', color: '#5a3e28', emoji: '🪲', wingspanMm: 115, fact: 'Adults have no mouth parts and cannot eat — they live only about a week, surviving on fat reserves from the caterpillar stage.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/75856962/medium.jpg' },
  1810477: { common: 'Cecropia Moth', scientific: 'Hyalophora cecropia', color: '#5a3e28', emoji: '🪲', wingspanMm: 160, fact: 'North America\'s largest native moth — its spectacular wingspan can reach 16 cm.', photoUrl: 'https://static.inaturalist.org/photos/38455915/medium.jpg' },
  1811219: { common: 'Atlas Moth', scientific: 'Attacus atlas', color: '#5a3e28', emoji: '🪲', wingspanMm: 250, fact: 'One of the world\'s largest moths by wing area — its wingtips are patterned to resemble the heads of snakes.', photoUrl: 'https://static.inaturalist.org/photos/416188682/medium.jpg' },
  1820993: { common: "Death's-head Hawkmoth", scientific: 'Acherontia atropos', color: '#5a3e28', emoji: '🪲', wingspanMm: 130, fact: 'The skull-shaped marking on its thorax and its ability to squeak loudly made it a symbol of terror in European folklore.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/31352989/medium.jpg' },
  1820780: { common: 'Hummingbird Hawk-moth', scientific: 'Macroglossum stellatarum', color: '#5a3e28', emoji: '🪲', wingspanMm: 58, fact: 'Hovers and feeds in daylight with a tongue longer than its body — routinely mistaken for a hummingbird.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/103024389/medium.jpg' },
  1819887: { common: 'Garden Tiger Moth', scientific: 'Arctia caja', color: '#5a3e28', emoji: '🪲', wingspanMm: 65, fact: 'When threatened, it flashes bright red hindwings and releases foul-smelling yellow fluid from glands behind its head.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/315591574/medium.jpeg' },
  1819956: { common: 'Peppered Moth', scientific: 'Biston betularia', color: '#5a3e28', emoji: '🪲', wingspanMm: 55, fact: 'The textbook example of evolution by natural selection — industrial soot turned trees black and the dark form became dominant.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/46891363/medium.jpeg' },
  1820770: { common: 'Elephant Hawk-moth', scientific: 'Deilephila elpenor', color: '#5a3e28', emoji: '🪲', wingspanMm: 65, fact: 'Its pink and olive coloring makes it one of the most striking moths in Europe — and it can see in color at night.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/31525728/medium.jpg' },
  7759088: { common: 'Rosy Maple Moth', scientific: 'Dryocampa rubicunda', color: '#5a3e28', emoji: '🪲', wingspanMm: 50, fact: 'Looks like a scoop of strawberry lemonade ice cream — its vivid pink and yellow coloring is unique among North American moths.', photoUrl: 'https://inaturalist-open-data.s3.amazonaws.com/photos/138311902/medium.jpg' },
  1820867: { common: 'White-lined Sphinx Moth', scientific: 'Hyles lineata', color: '#5a3e28', emoji: '🪲', wingspanMm: 80, fact: 'The most commonly seen sphinx moth in North America — often confused with hummingbirds at dusk.', photoUrl: 'https://static.inaturalist.org/photos/1372348/medium.JPG' },
}
