/**
 * Public changelog for /ships (earthatlas.org/ships/changelog). Public-facing: plain language, no internal
 * details (environments, bake versions, vendors, costs, unreleased work). Add entries newest first when a
 * change goes live; update COUNTS (with its date) only from verified production numbers.
 */

const S = {
  marinecadastre: { name: 'MarineCadastre AIS', href: 'https://hub.marinecadastre.gov/pages/vesseltraffic' },
  gfw: { name: 'Global Fishing Watch', href: 'https://globalfishingwatch.org' },
  gisis: { name: 'IMO GISIS', href: 'https://gisis.imo.org/Public/' },
  ct: { name: 'Climate TRACE', href: 'https://climatetrace.org' },
  wpi: { name: 'World Port Index', href: 'https://msi.nga.mil/Publications/WPI' },
  bcports: { name: 'BC Ports and Terminals', href: 'https://catalogue.data.gov.bc.ca/dataset/bc-ports-and-terminals' },
  osm: { name: 'OpenStreetMap', href: 'https://www.openstreetmap.org/copyright' },
  gem: { name: 'Global Energy Monitor', href: 'https://globalenergymonitor.org' },
  mep: { name: 'MEP Alliance', href: 'https://www.mepalliance.org/list-of-scrubber-fitted-ships' },
}

// The numbers come from lib/ships/changelogCounts.js. Production refreshes them daily into Blob (api/cron/ships-counts.js,
// .github/workflows/ships-counts.yml); the page reads that file (COUNTS_URL) and falls back to COUNTS_FALLBACK, the last
// numbers checked by hand (`zsh scripts/ships/prod.sh counts`, 2026-10-08).
export const COUNTS_URL = 'https://fxj3imydg9misw9w.public.blob.vercel-storage.com/ships/changelog-counts.json'
export const COUNTS_FALLBACK = {
  asOf: '2026-10-08', ships: 49339, scrubberShips: 594, terminals: 103, berths: 152, anchorages: 810, portVisits: 141344,
  incidents: 9228, ports: 8961,
  terminalVisits: { counted: 35522, estimated: 2797, terminalsWithVisits: 96, from: '2025-01', to: '2026-10' },
  terminalEmissions: { stays: 14243, co2eTonnes: 677263, terminals: 71, from: '2024-01', to: '2026-07' },
  anchorageStays: { counted: 25049, estimated: 6023, anchoragesWithStays: 114, from: '2025-01', to: '2026-10' },
  shipTracks: { minute: 4104779, hourly: 126603, total: 4231382 },
}

const fmt = (n) => Number(n).toLocaleString('en-US')
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const fmtYm = (ym) => `${MON[+ym.slice(5, 7) - 1]} ${ym.slice(0, 4)}`
const span = (x) => `${fmtYm(x.from)} – ${fmtYm(x.to)}`

/** A counts object (COUNTS_FALLBACK's shape) → the cards. { label, value, detail?, sources: [S.x | plain string] } */
export function buildCounts(n) {
  const tv = n.terminalVisits, as = n.anchorageStays, te = n.terminalEmissions, st = n.shipTracks
  return [
    { label: 'Ships', value: fmt(n.ships), sources: [S.gfw, 'US Coast Guard', 'Transport Canada', 'FCC', S.marinecadastre, 'Wikidata', 'Wikimedia Commons'] },
    { label: 'Ports', value: fmt(n.ports), detail: 'worldwide', sources: [S.wpi, S.ct, S.gfw, 'Fisheries and Oceans Canada'] },
    { label: 'Terminals', value: fmt(n.terminals), detail: `${fmt(n.berths)} berths`, sources: [S.bcports, 'US Army Corps of Engineers', 'WA Dept. of Ecology', S.osm, S.gem, S.gisis] },
    { label: 'Terminal visits', value: fmt(tv.counted + tv.estimated), detail: `by the kinds of ship each terminal serves, at ${fmt(tv.terminalsWithVisits)} terminals, ${span(tv)}: ${fmt(tv.counted)} counted from minute-by-minute AIS, ${fmt(tv.estimated)} estimated from hourly positions`, sources: [S.marinecadastre, S.gfw] },
    { label: 'Port visits', value: fmt(n.portVisits), detail: 'at ports worldwide', sources: [S.gfw] },
    { label: 'Ship emissions at terminals', value: `${fmt(te.co2eTonnes)} t`, detail: `CO₂e while stopped at the berths, from ${fmt(te.stays)} stops by the kinds of ship each terminal serves, at ${fmt(te.terminals)} terminals, ${span(te)}`, sources: [S.ct] },
    { label: 'Incidents', value: fmt(n.incidents), sources: ['US Coast Guard', 'NOAA IncidentNews', 'WA Dept. of Ecology'] },
    { label: 'Ships with scrubbers', value: fmt(n.scrubberShips), sources: [S.gisis, S.mep] },
    { label: 'Official anchorages', value: fmt(n.anchorages), sources: [S.marinecadastre, 'eCFR', 'Fisheries and Oceans Canada'] },
    { label: 'Ship tracks', value: fmt(st.total), detail: `one ship’s path in one month, 2015 to now: ${fmt(st.minute)} at minute-by-minute detail, ${fmt(st.hourly)} at hourly detail`, sources: [S.marinecadastre, S.gfw] },
    { label: 'Anchorage stays', value: fmt(as.counted + as.estimated), detail: `at ${fmt(as.anchoragesWithStays)} anchorages, ${span(as)}: ${fmt(as.counted)} counted from minute-by-minute AIS, ${fmt(as.estimated)} estimated from hourly positions`, sources: [S.marinecadastre, S.gfw] },
  ]
}

/** Is this a complete counts object (every field buildCounts reads)? Anything else keeps the fallback. */
export function validCounts(n) {
  const num = (v) => Number.isFinite(Number(v)) && Number(v) > 0
  const ym = (v) => /^\d{4}-\d{2}$/.test(v || '')
  return !!n && /^\d{4}-\d{2}-\d{2}$/.test(n.asOf || '') && ['ships', 'ports', 'terminals', 'berths', 'portVisits', 'incidents', 'scrubberShips', 'anchorages'].every((k) => num(n[k]))
    && ['terminalVisits', 'anchorageStays', 'terminalEmissions'].every((k) => n[k] && ym(n[k].from) && ym(n[k].to))
    && num(n.terminalVisits.counted) && num(n.anchorageStays.counted) && num(n.terminalEmissions.co2eTonnes) && num(n.shipTracks?.total)
}

export const COUNTS_AS_OF = COUNTS_FALLBACK.asOf
export const COUNTS = buildCounts(COUNTS_FALLBACK)

export const COVERAGE_NOTE = 'Detailed ship tracks cover the Salish Sea for Jul 2025 – Jun 2026; US-wide tracks cover 2015 onward; hourly lines (Global Fishing Watch) cover British Columbia and Alaska from Jan 2025 and the Salish Sea and US West Coast from Jul 2026, updated daily.'

// Newest first. { date, area, text }
export const ENTRIES = [
  { date: '2026-10-09', area: 'Ship cards', text: 'A ship’s name is now shown once when its sources spell it differently only by spaces or punctuation. For example, the ship broadcasting PALANCA RIO, which Global Fishing Watch’s registry data lists as PALANCARIO, now has one name row listing both sources, and the card, search results and lists show the spelling that reads properly (PALANCA RIO). Both original records are kept exactly as each source gave them. This applies to every ship.' },
  { date: '2026-10-09', area: 'Ship tracks', text: 'Fixed a visible line in the ship tracks where the detailed Salish Sea tracks meet the US-wide tracks (for example across Texada Island): the US-wide tracks drew over the detailed ones inside the Salish Sea, so traffic there looked doubled. For January 2025 to June 2026, the months with detailed Salish Sea tracks, the US-wide tracks now stop at the edge of the Salish Sea area, and each stretch of water is drawn once. The Kind of ship “Narrow to” note about zooming in now appears only for months before 2024, where it still applies.' },
  { date: '2026-10-09', area: 'Ship tracks', text: 'The Kind of ship “Narrow to” picks (Cruise ship, Ferry, Oil tanker, Container ship and the rest) now work when zoomed out across the whole US-wide track map, not only inside the detailed Salish Sea area, for January 2024 to June 2026. Before, zoomed-out tracks outside the Salish Sea could only be filtered by broad kind, so picking Cruise ship there still showed every passenger vessel north of the Strait of Georgia. A track is narrowed by the ship’s kind in EarthAtlas’s own ship records, the same records the zoomed-in map uses, so zooming in and out now shows the same ships.' },
  { date: '2026-10-09', area: 'Map', text: 'On a computer, /ships now opens on the Salish Sea at a closer zoom, centred on the Strait of Juan de Fuca, so terminals and harbours show straight away. On phones it still opens on the whole Salish Sea.' },
  // Numbers from prod.sh counts 2026-10-08 (production, read only), the same figures as the counts panel's built-in ones.
  { date: '2026-10-08', area: 'Changelog', text: 'The numbers at the top of this page now update every day, after the day’s new ship data comes in, and each one answers a single question with everything we hold combined, counted the same way the map’s cards count it. Ships with scrubbers: 594 ships, from the IMO’s scrubber notifications and the MEP Alliance lists together (a ship on both counts once). Ship tracks: 4,231,382 ship tracks (one ship’s path in one month) from 2015 to now, 4,104,779 at minute-by-minute detail and 126,603 at hourly detail. Terminal visits: 38,319 at 96 terminals, Jan 2025 – Oct 2026, counting only the kinds of ship each terminal serves, as its card does. Anchorage stays: 31,072 at 114 anchorages. Ship emissions at terminals: 677,263 t CO₂e from ships stopped at the berths, Jan 2024 – Jul 2026 (Climate TRACE). Ports: 8,961 worldwide, with a port listed by several sources counted once. Ships: 49,339.' },
  { date: '2026-10-08', area: 'Emissions', text: 'Climate TRACE’s ship emissions estimates now update on their own each month, soon after Climate TRACE publishes new data: the Emissions tab on ship cards (each trip and port stay) and the port-stay emissions on terminal cards. This adds January – July 2026, which were missing before (they had shown as months outside our copy). Both now say which months they cover.' },
  // Numbers from prod.sh import-bc-permits 2026-10-08 (production): Metro Vancouver 20 permits at 18 BC terminals, 24 documents,
  // 15 dock quotes (was 8 permits at 8 terminals).
  { date: '2026-10-08', area: 'Terminals · Permits', text: "Metro Vancouver air quality permits now come from Metro Vancouver’s own list of current permits and its site search, and cover 18 BC terminals (20 permits, up from 8). Newly shown: Westshore (GVA0153, which names loading of marine vessels at Berths 1 and 2), G3 (GVA1080), Cargill (GVA0618), Alliance Grain (GVA0619), Cascadia (GVA1216), Pacific Terminal (GVA0616, held by Bunge), Fibreco (GVA0248), Lantic (GVA0571) and Lehigh’s Delta cement terminal (GVA0175). Updated to Metro Vancouver’s current versions: Chemtrade’s renewal (GVA1281, issued April 30, 2026, replacing GVA0010), Vancouver Wharves (GVA0086, amended October 7, 2026), Suncor Port Moody (GVA0200, amended March 27, 2026), Richardson (its permit GVA0617 expired November 30, 2025; it now holds approval GVU1296 while its renewal is under review) and Lafarge Richmond (GVA0154, May 2025). Fifteen of these permits name the dock itself, quoted with where they say so. Where a terminal’s permit isn’t in Metro Vancouver’s list or search, the tab says what was searched." },
  { date: '2026-10-08', area: 'Reports', text: 'While the scrubber report is being put together, it now shows a little ship bobbing on the waves with a spinner and a line saying what is being counted, instead of a plain “loading” message.' },
  { date: '2026-10-08', area: 'Reports', text: 'The scrubber report now names the ships. A new Ships section lists every scrubber-fitted ship in the report with its type, flag, operating company (from the MEP Alliance lists), registered owner, and scrubber: open loop (washwater discharged to the sea), hybrid or closed loop as notified to the IMO, or “type not reported”, with the maker; its calls, where, and month by month. Filter by ship type, scrubber type or operator. An Operators section ranks the companies by calls, and a new headline number gives the share of calls made by open-loop ships (Washington, January 2025 – June 2026: 41%; hybrid 28%, type not reported 31%). The report is now titled “Scrubber-fitted ship calls at Washington ports, terminals and refineries”. On the /ships map, the Scrubber-fitted filter and the foot of the left panel link to the report, and each terminal card shows its scrubber-ship calls with a link that opens the report at that terminal. A new “Focus Geography” choice narrows the whole report to one port (for example the Port of Seattle), county, city or town, type of facility, or a single facility: title, numbers, tables, chart, operators, ships and where else those ships call; it is part of the link, so a focused report can be shared or printed. Links to a terminal on the map now open zoomed to that terminal.' },
  { date: '2026-10-08', area: 'Reports', text: 'Scrubber report: the opening now names scrubbers by their formal name (exhaust gas cleaning systems) and says plainly that a call by a scrubber-fitted ship does not show the scrubber was running at the berth. Ports in the month-by-month table are grouped by port, with each port’s own totals (for example the Port of Seattle’s cruise, container and grain docks together). The report now counts only passenger, cargo and tanker ships: tugs, fishing boats and pleasure craft are not included, which also removes a few calls by boats that only shared a scrubber ship’s name or radio number (Washington, January 2025 – June 2026: 1,174 calls by 274 ships).' },
  // Numbers from the production imports 2026-10-08 (prod.sh import-facilities / import-wa-air / import-cer): WA 54 facilities, 419
  // permits, 666 documents; 57 of 59 WA terminals with a facility, 2 none-found; SEPA per permit 170 (13 linked, 17 exempt, 1 stated,
  // 139 none); air agency permits 16; CER Westridge: 37 inspections/meetings, 12 incidents, 2 maintenance, 1 contamination, 12 conditions, 2 orders.
  { date: '2026-10-08', area: 'Terminals · Permits', text: "Permits now cover every Washington terminal on the map: all 59, including the Seattle and Tacoma container and cruise terminals, Everett, Bellingham, Port Angeles, Olympia, Grays Harbor and the Columbia River terminals at Vancouver, Kalama and Longview. Each Permits tab names the facility behind the dock (for port-run terminals, the port’s own permits) with its EPA and Washington Ecology permits, documents, enforcement and SEPA reviews; two terminals (West Sitcum in Tacoma and Weyerhaeuser’s Longview log dock) say plainly that no facility was found. Washington terminals now hold 419 permits and 666 permit documents, and the SEPA answer for each permit now covers 170 permits. Air permits from the Olympic Region and Southwest clean air agencies now show for Grays Harbor Terminals 1 and 4, Port Angeles, Olympia, United Grain in Vancouver and EGT in Longview, several quoting the permit’s own words about the dock (for example “East Ship Loader Spout” at EGT)." },
  { date: '2026-10-08', area: 'Terminals · Permits', text: "The Westridge Marine Terminal’s Permits tab now includes the Canada Energy Regulator’s records for the terminal: its 37 inspections and meetings since 2016 with their 153 findings and what the regulator required (for example notices of non-compliance), 12 incidents (fires, two serious injuries and one adverse environmental effect; none involved a spill), a contaminated-site record under monitoring, 2 maintenance activities, the 12 Trans Mountain Expansion conditions about the marine terminal itself (each quoted), and two inspection officer orders: BL-001-2023 on safety headwear and LH-001-2020 on COVID-19 protocols. A record is shown only when the regulator’s own data names the Westridge terminal; each links to the regulator’s published data and, where there is one, its filing." },
  { date: '2026-10-08', area: 'Sources', text: "DNR aquatic land lease records now read in plain words: lease number, kind, lessee, status, start date, size, county and a link to show the lease on the map. DNR does not publish lease documents or end dates online; the page says so." },
  { date: '2026-10-08', area: 'Reports', text: 'The scrubber report’s month-by-month table now fits the page: every month is shown across the full width of the window (and of the printed page) without scrolling sideways; under each number is how many different ships made those calls. The report now lists only the facilities it has numbers for, and the three terminals NOAA’s receivers don’t reach (Squamish Terminals, Woodfibre LNG and the Texada Island quarry dock) are counted from hourly ship positions, marked ≈, for every month. Explanations of how the numbers are made are gathered under “How this is counted” at the end.' },
  { date: '2026-10-07', area: 'Reports', text: 'The scrubber report now prints: “Print or save as PDF” at the top produces a landscape copy with the month-by-month table across the page width, the chart, the place breakdown, the worldwide port visits and the method notes, without the on-screen controls. The top of the report now states plainly what it covers: period, area, the date of the data and its web address. The CSV download was removed.' },
  // Numbers from the production imports 2026-10-07 (prod.sh import-facilities / import-wa-leases / import-wa-air): SEPA per permit 95
  // permits (13 linked to 24 reviews, 16 exempt, 1 stated, 65 none found); DNR 13 leases at 12 terminals, 25 port-managed; Whatcom
  // shoreline 2; air: 8 agency permits (7 PSCAA + 1 ORCAA registration) at stored facilities, 5 dock quotes.
  { date: '2026-10-07', area: 'Terminals · Permits', text: "Every Washington permit now says which SEPA environmental review covers it. On a terminal’s Permits tab each water, air and hazardous-waste permit carries a small SEPA note, and the permit’s own page has a SEPA review tab. A review is linked to a permit only on written evidence: the SEPA record names the permit or an approval the permit includes, the permit’s fact sheet names the SEPA record, or both describe the same project by name. Each linked review shows its lead agency, decision and date, with the quote that ties it to the permit. Where the permit’s own fact sheet says SEPA doesn’t apply (for example, state law exempts reissuing a wastewater discharge permit), that sentence is quoted with its page. Where nothing was found, the page says “No SEPA review found for this permit” and lists every search made. Across 95 permits: 13 are linked to 24 SEPA reviews, 16 quote an exemption, 1 describes a review that isn’t in the SEPA Register, and 65 have none found (mostly stormwater general-permit coverages, which have no fact sheet). The Husky container terminal in Tacoma and Grays Harbor’s Terminal 2 now have their permits too." },
  { date: '2026-10-07', area: 'Terminals · Permits', text: "Washington terminals’ Permits tabs now show the state-owned aquatic land under the dock. Washington’s Department of Natural Resources leases the tidelands and bedlands beneath most docks; 13 of those leases are shown at 12 terminals (for example BP Cherry Point, Phillips 66 Ferndale, the Marathon and HF Sinclair refineries at Anacortes, NuStar Tacoma and Point Wells), each with its lease number, lessee, kind, status, start date and acres, from DNR’s public lease map. DNR’s public data does not include end dates, so the tab says so. Another 25 terminals sit on state land managed by their port (Seattle, Tacoma, Bellingham, Anacortes, Everett, Port Angeles, Olympia, Vancouver, Kalama and Grays Harbor) under a port management agreement, shown as such. For the Petrogas wharf at Ferndale, Whatcom County’s two shoreline permits for work at the dock (a loading arm and dredging, 2020) are listed with their notices and SEPA records." },
  { date: '2026-10-07', area: 'Terminals · Permits', text: "Washington terminals’ Permits tabs now include permits from the local clean air agencies. Puget Sound Clean Air Agency’s orders of approval are shown for the Tacoma LNG plant (including the fueling system for TOTE’s ships, and a proposed revision open for public comment until November 13, 2026), SeaPort Sound Terminal (marine loading of natural gasoline), Schnitzer’s Tacoma yard and Ash Grove’s Seattle cement plant, each with its number, holder, dates, status and the agency’s documents; where a permit names the dock itself, that sentence is quoted. Puget Sound Clean Air Agency’s notices of violation and penalties in EPA’s records are now labelled as the agency’s. Where an agency publishes nothing for a terminal, the tab says what was searched." },
  { date: '2026-10-07', area: 'Terminals · Ports', text: 'Emissions tabs now chart one or two months the way the Ships tab does. Climate TRACE’s port stays (emissions from ships stopped at a terminal’s berths) are shown day by day, by the day each stay began. Refinery and ship-voyage emissions are published by Climate TRACE only per month, so for one or two months their single bars are gone and the total and the list of gases remain; three months or more still show a bar per month.' },
  // Terminals 103 / berths 152: production import 2026-10-07 (prod.sh import-terminals; +4 T5/T18 AIS-estimated berths).
  { date: '2026-10-07', area: 'Terminals · Reports', text: 'British Columbia’s container, vehicle and cruise terminals are now on the map and in the scrubber report: GCT Deltaport at Roberts Bank, Centerm and GCT Vanterm in Vancouver, Fraser Surrey Docks, the Annacis Island vehicle terminal, Lynnterm, Canada Place and Ballantyne Pier, Victoria’s Ogden Point, and Nanaimo’s Assembly Wharf and cruise terminal (103 terminals in all). Deltaport, Centerm and Seattle’s Terminals 5 and 18 have long berths, so their berth points are also estimated from where container ships actually stopped over a year of NOAA AIS (marked as estimated on the terminal card). Ships that broadcast only a general “cargo” type now count at container, ro-ro and general-cargo terminals, the way a general “tanker” already counts at oil docks.' },
  { date: '2026-10-07', area: 'Ship tracks', text: 'Fixed the counts on the “Narrow to” filters (Cruise ship, Ferry and the rest) when zoomed out over months after NOAA’s latest: they showed 0 while the picked ships’ lines were drawn on the map, because zoomed-out hourly-position tiles don’t carry which ship each line belongs to. They now show no number and say “Zoom in to count the ships in view”; from zoom 9 the counts work for those months too.' },
  // Numbers from prod.sh import-bc-permits 2026-10-07 (production): Metro Vancouver 8 permits, 10 documents, 4 dock quotes;
  // 24 BC terminals inside Metro Vancouver, 9 outside; BC EMA 66 (Shell 11258 now accepted for Shellburn).
  { date: '2026-10-07', area: 'Terminals · Permits', text: 'BC terminals’ Permits tabs now include Metro Vancouver air quality permits, which most terminals around Burrard Inlet and the Fraser River need. Eight terminals have one (GVA0205 Pacific Coast Terminals, GVA0081 Neptune, GVA0261 Shell Burnaby, GVA1167 Fraser Grain, GVA0294 Imperial Oil Ioco, GVA0200 Suncor Port Moody, GVA0617 Richardson and GVA0154 Lafarge Richmond), each with its holder, address, issue and amendment dates, expiry, and a link to the permit document. For four of them the permit names the dock itself, quoted with where it says so, for example Neptune’s “loading of marine vessel with coal from two ship loaders”. Where a renewal or amendment is under review (Richardson, Suncor), the tab says so and links Metro Vancouver’s public notice. Terminals outside Metro Vancouver’s region (Squamish, Howe Sound, Sechelt, Texada and Vancouver Island) say so, and the rest say no permit was found. Shell’s permit also confirms its Burnaby terminal address, so its BC waste-discharge authorization now shows there too.' },
  { date: '2026-10-07', area: 'Reports', text: 'The scrubber report now runs past NOAA’s latest month: July 2026 onward is estimated from hourly ship positions (Powered by Global Fishing Watch), marked ≈ in every table, chart and download, and replaced by NOAA’s counts as NOAA publishes each month. An estimated stop is credited to a terminal only when it is the one nearby terminal that fits the kind of ship; stops that could be at either of two neighbouring terminals are left out of the rows and counted in a note. Estimates now also cover the lower Columbia River (Vancouver, Kalama, Longview) and the cruise, container and other terminals added today. New section, “Where else these ships call”: every port the report’s scrubber-fitted ships visited worldwide in the period, by country and by port (Global Fishing Watch port visits; port names from the World Port Index), for the ships that called in Washington, in British Columbia, or all of them.' },
  // Terminals 92 / berths 127 / 59 WA terminals with county, city and owner: read-only production query 2026-10-07 after
  // prod.sh import-terminals + terminal-places. New months / recounts are filled by the ships-noaa-month workflow.
  { date: '2026-10-07', area: 'Reports · Terminals', text: 'New: a report on scrubber-fitted ships calling at terminals, at earthatlas.org/ships/reports/scrubbers. For each port, terminal and refinery it shows, month by month, how many calls ships fitted with exhaust-gas scrubbers made and how many different scrubber ships made them, grouped as ports (docks a public port district owns), other terminals and refineries, with totals, a chart that opens day by day, a breakdown by county and city or town, the list of ships at each facility, and a CSV download. Pick Washington, British Columbia or both, and any period. A call is a ship stopped at a berth, counted from NOAA’s minute-by-minute AIS; a ship counts as scrubber-fitted when it is in the IMO’s scrubber notifications or on the MEP Alliance lists. 33 terminals were added for it, so the map now has 92: Seattle’s Smith Cove and Bell Street cruise terminals, the Seattle and Tacoma container terminals, TOTE, Tacoma’s Terminal 7 and Blair Waterway wharf, the Everett, Port Angeles, Bellingham and Olympia port terminals, and for the first time the Columbia River (Vancouver, Kalama, Longview) and Grays Harbor. Every Washington terminal now carries its county, its city or town (US Census Bureau) and who owns the dock (US Army Corps of Engineers dock records). Calls at the new terminals, and January to June 2025, are added as they are counted; until then the report says “not counted yet”, never zero. Dated editions of the report can be frozen so cited numbers never change. “How this is sourced” now also says what kind of data each part is and how current it is, and why tugs are counted only from NOAA’s per-minute positions.' },
  // 1,321 = ships in production with a USCG PSIX "Freight Ship · General" record (read-only count 2026-10-07).
  { date: '2026-10-07', area: 'Ship kinds · Terminals', text: 'Ships the U.S. Coast Guard lists as “Freight Ship · General” are now classed as general cargo / multi-purpose ships instead of plain “Cargo” (1,321 ships). Grain and other bulk terminals count general cargo ships, so visits by these ships now count there instead of being listed as “could be”, for example POWER GLOBE at Seattle’s Terminal 86.' },
  // Numbers from prod.sh import-bc-permits 2026-10-07 (production): 33 facilities, 65 EMA authorizations, 115 NRCED records shown
  // (241 company-only matches kept, not shown), 7 EAO projects, 100 documents; 14 terminals with no authorization found.
  { date: '2026-10-07', area: 'Terminals · Permits', text: 'Permits now cover every British Columbia terminal on the map too: all 33, from Westridge, Westshore, the Burnaby refinery and the Burrard Inlet fuel and chemical terminals to the Fraser River, Squamish, Howe Sound and Vancouver Island docks. Each BC terminal’s Permits tab names the site behind the dock and lists its waste-discharge authorizations under BC’s Environmental Management Act (65 in all, from the province’s public register, with the address, what each covers, when it was issued and whether it is still in force), the inspections and enforcement records BC’s Natural Resource Compliance and Enforcement Database holds for it (115, each with its result and the inspection report), and any BC Environmental Assessment Office review of a project there (7, such as the Trans Mountain Expansion at Westridge and the Tilbury LNG expansion). A record is shown only when it is issued to the site’s company and names one of its authorizations or its location. Where no authorization was found (14 terminals, mostly grain terminals), the tab says so in plain words. Click any authorization for its own page.' },
  // Accuracy figures from the June 2026 check (docs/SHIPS_ACTIVITY_CHECK_2026-06.md, read-only against production 2026-10-06/07);
  // 31 of 112 Salish anchorages contain no 0.01° grid point (activity_inputs.json, production polygons).
  { date: '2026-10-07', area: 'Terminals · Anchorages · Search', text: 'Terminal and anchorage activity now continues past NOAA’s latest month. NOAA’s per-minute AIS, which counts visits berth by berth, is published about three months late (it runs through June 2026); for the months after that, terminal visits and anchorage stays are now estimated from hourly ship positions (Powered by Global Fishing Watch), marked ≈ and linked to their own record, and replaced by NOAA’s counts as NOAA publishes each month, which now loads by itself. Hourly positions sit on a grid about 1 km across, so neighbouring terminals closer than that can’t be told apart: at the Anacortes refineries, Westridge and Shellburn, the Tacoma oil docks and Seattle’s Harbor Island the card shows a range (for example ≈0–12 visits: none can only be this terminal, 12 could be this one or its neighbour) and names the neighbour. Tug visits are not counted from hourly positions (tugs moor right beside the terminals they serve). Checked against NOAA’s June 2026 counts in the Salish Sea: 90% of cargo-ship and tanker visits found, and 90% of visits credited to one terminal were at that terminal. Anchorages now open a card like the terminals’ (Ships and About tabs, its own link) instead of a small popup; 31 of the 112 Salish Sea anchorages are smaller than the grid and say so instead of showing zero. With one or two months picked, the charts on both cards show each day. And the “Fly to a place” search now finds the ports, terminals, anchorages and facilities /ships tracks, by name or another name (Vendovi South is also found as “Anacortes”), and opens their card.' },
  // Verified 2026-10-07 after prod.sh import-facilities (coverage 17 at 14 terminals; PSCAA documents 8) and via the live API
  // (wa-us-oil-tacoma 4 PSCAA documents; wa-nustar-tacoma status idle).
  { date: '2026-10-07', area: 'Terminals · Permits', text: 'More permits now say in their own words which dock they cover: 17 quotes at 14 Washington terminals (up from 6 at 3), each linking to the permit document and the page it is on, so you can see that a permit covers the dock itself, not just the plant behind it. Puget Sound Clean Air Agency’s Title V air operating permits are now listed for the U.S. Oil Tacoma refinery and the Ash Grove Seattle cement plant, with the permit, its statement of basis and their attachments (8 documents). The NuStar Tacoma dock is now marked idle: Washington Ecology’s fact sheet for its water permit (effective 1 Sep 2026) says its marine loading dock has been discontinued; the tank farm and truck racks still operate.' },
  // Numbers verified against production 2026-10-07 (read-only counts after prod.sh import-facilities): 27 facilities at 26 WA
  // terminals, 272 permits (13 WA-PARIS state-only), 4,339 documents, 2,353 violations, 204 SEPA reviews, 6 dock citations.
  { date: '2026-10-07', area: 'Terminals · Permits', text: 'Permits now cover every Washington terminal on the map: all 26, from the Cherry Point and Anacortes refineries to the Tacoma tideflats terminals, the Harbor Island fuel terminals, Tacoma LNG, the grain, cement and scrap-metal docks, two Navy fuel piers and Port Angeles. Each terminal’s Permits tab names the facility behind the dock (27 in all) and lists its permits and program records from EPA and Washington Ecology (272, including 13 state-only permits EPA doesn’t track), with 4,339 documents linked to the agencies’ copies, 2,353 recorded violations, enforcement actions and inspection reports, and 204 environmental (SEPA) reviews of their projects. Where a facility has no record of a kind (for example no SEPA review on file), the tab says so.' },
  // Numbers verified against production 2026-10-06 (read-only counts after prod.sh import-facilities): 3 facilities, 59 permits
  // (2 WA-PARIS state-only), 1,274 documents, 96 SEPA reviews, 358 violations, 5 permit↔dock coverage citations.
  { date: '2026-10-06', area: 'Terminals · Permits', text: 'Terminal cards now have a Permits tab, starting with three Salish Sea facilities: the BP Cherry Point refinery, the Marathon Anacortes refinery, and Tesoro Logistics, which owns the Marathon refinery’s wharf. It lists every permit and program record EPA and Washington Ecology hold for the facility behind the dock (59 in all, including 2 state-only permits EPA doesn’t track), and says plainly that these are the facility’s permits, not the dock’s; a permit is marked “covers this dock” only where its own text names the dock, quoted with the page (5 so far). Click a permit to open its own page: who issued it, its versions and dates, and tabs for its documents (1,274 in all, linked to the agency’s copies: permits, fact sheets, inspection reports, penalty notices and orders), its enforcement actions and inspections (each linked to the agency’s letter, order or EPA case report where one exists, with Ecology’s decision and the violations behind it), its violations (358, with the measured value, the limit and the outfall), and the environmental (SEPA) reviews of the facility’s projects (96, from Washington Ecology’s SEPA Register). Terminal cards also gain “Show on map”.' },
  // Numbers from the published hourly-line month manifests 2026-10-06 (Jul 480,118 lines / 17,632 ships; Aug 483,657 / 17,797;
  // Sep 320,841 / 15,510).
  { date: '2026-10-06', area: 'Ship tracks · Ship cards', text: 'The hourly ship-track lines (Powered by Global Fishing Watch) now cover the US West Coast, from the Salish Sea south to San Diego, from July 2026 on, updated daily about four days behind. With them, July–September 2026 now hold 480,118, 483,657 and 320,841 lines from 17,632, 17,797 and 15,510 ships. Where NOAA’s per-minute AIS exists (through June 2026) its tracks are still the ones shown, and NOAA replaces the hourly lines when it publishes a newer month. Also fixed: clicking an hourly line of a ship that EarthAtlas had just looked up could still say “Not yet in EarthAtlas’s ship records” for a minute or so; the ship card now opens right away.' },
  { date: '2026-10-02', area: 'Ship cards · Ship tracks', text: 'Hover over a picked ship’s own tracks to see where it was: a top-down ship icon sits on the line pointing the way it was heading, drawn by kind of ship (tanker, cargo, cruise ship, ferry, fishing boat, tug, sailboat) and sized by its length, with its name, kind of ship, the local time there, its speed and its heading. On NOAA tracks and on estimated (dashed) paths the time is spread along the line from its start and end (marked ≈) and the speed is the average for the line. Ship cards also gain “View in” links to the ship’s public page on MarineTraffic (by IMO number), VesselFinder and MyShipTracking (by MMSI).' },
  { date: '2026-10-02', area: 'Ship records', text: 'Every ship seen in the hourly ship-track lines (British Columbia, Alaska and the Salish Sea since July 2026) is being added to EarthAtlas’s ship records with what it broadcast: name, MMSI, call sign, IMO number and flag (AIS, as served by Global Fishing Watch), and Global Fishing Watch’s vessel type, each with the first and last time it was seen. Ships we already held are linked by their IMO number, or by MMSI plus the same name or call sign; an MMSI alone never merges two ships. So clicking one of these lines now opens a ship card, filled in as far as the data goes. Records are added for each completed month.' },
  { date: '2026-10-02', area: 'Ship tracks', text: 'The hourly ship-track lines for British Columbia and Alaska are being re-drawn against the full coastline: some lines cut straight across islands and headlands (for example Digby and Kaien Islands at Prince Rupert) because part of the coastline was missing when they were drawn. Clicking an hourly line of a ship that is not yet in our ship records now shows the name, flag and IMO number the ship broadcast (AIS), as served by Global Fishing Watch, instead of only “no identity record”.' },
  // Numbers from the published GFW index 2026-10-02 (21 months, 1,970,155 lines; ships per month 1,647–12,206).
  { date: '2026-10-02', area: 'Ship tracks', text: 'Ship tracks now reach British Columbia and all of Alaska, and the Salish Sea no longer stops at NOAA’s latest month. Where NOAA has no per-minute AIS, the lines come from hourly ship positions (Powered by Global Fishing Watch), so they are straighter than NOAA’s; where a straight line between two hours would cross land, EarthAtlas estimates the path along the water from official coastlines (OpenStreetMap, Alaska DNR, Natural Resources Canada), keeping off tidal flats and marshes and following the lanes ships actually use, and draws it dashed. Each line is typed from EarthAtlas’s own ship records where we know the ship, so the Kind of ship filters work on them (the Valdez tanker route now shows under Tanker). Jan 2025 – Sep 2026 for British Columbia and Alaska, and Jul – Sep 2026 for the Salish Sea: 1,970,155 lines, from 1,647 ships in December 2025 to 12,206 in August 2026. Updated daily, about four days behind. When NOAA publishes a month, its tracks replace the hourly ones there.' },
  { date: '2026-10-02', area: 'Ship tracks', text: 'The numbers on the Ship tracks filters (the “Narrow to” kinds, such as Oil tanker, and Scrubber-fitted) now count the ships whose tracks are on the map right now, for the months and filters you have picked, and they update as you move the map. Each number is what that filter will draw: turn it on and exactly that many ships’ lines remain. Each ship counts once, however many trips it made. The note under Scrubber-fitted also gives the total on record.' },
  { date: '2026-09-30', area: 'Sharing', text: 'A link to a particular /ships map view now previews with a picture of that view (where the map is, and which layers are on). Links to earthatlas.org/ships itself now preview with their own picture, “The open record of every ship”, instead of the general EarthAtlas card, and the page’s title and description now read “Ships — the open record of every ship”: where it’s sailed, what it’s burned, and the impact it may leave behind.' },
  // Numbers below verified against production 2026-09-30 (read-only counts after the anchorage and MEP imports):
  // 15,448 stays / 3,338 vessels / 108 anchorages; Vendovi South 87 stays by 51 ships; MEP 334 by IMO, 31 + 32 by name;
  // scrubber filter 594 ships (IMO 460, MEP 365, both 231).
  { date: '2026-09-30', area: 'Ship cards', text: 'Clearer ship cards. A ship’s scrubber (exhaust gas cleaning system) now has its own highlighted block near the top of the Overview, with the official IMO filing and the MEP Alliance reports each on their own line and linked to their source. The owner and operator now sit right under the ship’s name. When no source has emissions for a ship, the Emissions tab now says so in one line. The History tab is now the last tab.' },
  { date: '2026-09-30', area: 'Ship cards · Ship tracks', text: 'Ship cards now also show when a ship is on the MEP Alliance scrubber lists, beside (never merged with) the scrubber filings flag states make to IMO: the list, the date reported, and the owner and charterer the list names, each linked to its source. These are reported facts from an advocacy group, not registry records, and are labelled that way. MEP Alliance lists 3,536 scrubber-fitted (or pending) bulk carriers, tankers, container ships and cruise ships by IMO number, 334 of them ships we hold, and 492 reported voyages of 309 named ships. That voyage list gives no IMO number, so EarthAtlas matched 63 of those ships by name: 31 confirmed by a second fact, and 32 marked “matched by name (inferred)” because they are the only large ship of that name seen in the Salish Sea. New “Scrubber-fitted” filter under Ship tracks shows only the tracks of the 594 ships with a scrubber filed with IMO (460) or on the MEP Alliance lists (365; 231 are on both).' },
  { date: '2026-09-30', area: 'Anchorages', text: 'Official anchorage areas are now on the map (inside Ports & terminals, from zoom 8): 33 CFR anchorages in US waters, Fisheries and Oceans Canada’s active commercial anchorages in BC, and the Puget Sound anchorages the Coast Guard’s traffic service uses without a legal designation (clearly marked). Click an anchorage’s name for who anchors there: EarthAtlas counted every stay from AIS (a ship stopped, under 0.5 knots, inside the area for an hour or more) with the number of ships, ship-hours, the kinds of ship and the ships that spent the most days there, each linked to the count’s record. 15,448 stays by 3,338 vessels at 108 Salish Sea anchorages, Jul 2025 – Jun 2026. Vendovi South (off Vendovi Island): 87 stays by 51 ships, 36 of them tankers (SILVER LONDON 14 days, ALTHEA 13, HIGH SEAS 11). Pleasure boats and other small craft are counted too and shown apart by kind. Anchorages now also show other names they go by, each with its source: Vendovi South is “Vendovi Island South (VIS)” to the Coast Guard’s Puget Sound traffic service (its user’s manual) and Vendovi East is “Vendovi Island East (VIE)”; Global Fishing Watch files Vendovi South under “Anacortes”, so port visits there read Anacortes. Anchorages outside the area our AIS covers say so instead of showing zero.' },
  { date: '2026-09-29', area: 'Ship cards', text: 'The Emissions tab now shows a ship’s verified EU MRV emissions reports above Climate TRACE’s modelled estimates, as two separate blocks labelled “verified” and “estimate”; the two are never added together. 1,767 of our ships have at least one report (2018–2025), 1,652 of them seen in the Salish Sea. The newest year shows CO₂ (from 2024 also methane, nitrous oxide and CO₂-equivalent), CO₂ at berth, fuel burned, hours at sea, CO₂ per nautical mile, the ship’s design efficiency rating and who verified the report; earlier years get one line each. Every figure links to the European Maritime Safety Agency’s page for that ship and year. These reports cover only voyages to, from and between EU/EEA ports and time at berth there, so for ships trading mostly in the Pacific they are far below the ship’s whole-year emissions (EURODAM: 298 t CO₂ in 2024).' },
  // Numbers below verified against production 2026-09-29 (tc4 import + readTerminalCard on the prod DB):
  // 37,554 visits at 52 terminals; BP Cherry Point 1,122; HF Sinclair 1,039.
  { date: '2026-09-29', area: 'Terminals', text: 'Official berth facts on terminal cards (About tab), each linked to its document: berth names, lengths and depths from the Pacific Pilotage Authority’s berth list (November 2025) and the Port of Vancouver’s berth soundings sheets, for Vancouver Wharves (Berths 1, 2/3, 4 and 5), Richardson International (one berth) and Pacific Terminal (Pacific Elevator 4). Where BC’s terminal list disagrees (it gives Richardson 108 m; the pilotage list 183 m, the port sheet 164 m), both are shown. The newer document now sets how close a stopped ship must be to count: Vancouver Wharves Berth 1 (231 m) within 166 m instead of 150 m; Pacific Terminal’s berth (270 m between mooring dolphins, not 305 m) within 185 m instead of 203 m. Ships counted at these three terminals are unchanged; 20 more other vessels are listed at Vancouver Wharves and 18 fewer at Pacific Terminal. 37,554 terminal visits in all, Jul 2025 – Jun 2026.' },
  { date: '2026-09-29', area: 'Terminal visits', text: 'Chemical tankers now count as visits at refinery docks and crude and fuel-product terminals, the same rule the Climate TRACE port stays already use (many product tankers, which load refined fuel at these docks, are listed as chemical tankers). 7 more visits, Jul 2025 – Jun 2026: BP Cherry Point 1,122 (was 1,120), HF Sinclair Puget Sound 1,039 (was 1,034); other oil docks unchanged.' },
  { date: '2026-09-29', area: 'Terminals', text: 'Terminal cards’ Emissions tab now shows Climate TRACE’s estimate for ships while they are stopped at the terminal’s own berths (port stays): 7,262 stays by 2,092 ships of the kinds each terminal serves, at 46 of the 59 terminals, 2024–2025, about 262,000 t CO₂e. Chemical tankers count at refinery and oil docks. Stays by other kinds of ship at the same spot are listed apart, not added in; stays that could belong to two neighbouring terminals are left out.' },
  { date: '2026-09-29', area: 'Ship cards', text: 'The Emissions tab now says who tracked the ship for Climate TRACE: OceanMind (large ships) or Global Fishing Watch (smaller ships), and shows the ship’s deadweight and Climate TRACE’s modelled CO₂ per nautical mile for the 4,379 ships OceanMind tracks. Voyage and port-stay figures updated to Climate TRACE’s latest release and extended north to Vancouver harbour, Roberts Bank, Howe Sound and Nanaimo: 15,817 Climate TRACE ship entries with trips or stays that began in 2024–2025.' },
  { date: '2026-09-28', area: 'Terminals', text: 'Berths estimated from where ships actually stop, for Richardson and Vancouver Wharves (North Vancouver), whose one listed point missed the berths ships use. Each estimate is labelled as such on the terminal card, with how many ships and stops it rests on. Richardson now shows 42 visits by 24 bulk carriers (it showed none), plus 180 visits by cargo ships whose exact kind isn’t stated; Vancouver Wharves 64 visits by 53 ships, up from 25.' },
  { date: '2026-09-28', area: 'Terminals', text: 'Real berth positions for 8 multi-berth terminals (Westshore, Neptune, Westridge, Alliance Grain, Cargill, BP Cherry Point, Crofton, Pacific Coast Terminals), so ships at every berth are counted. Westshore now shows 62 visits by 52 bulk carriers.' },
  { date: '2026-09-28', area: 'Terminals', text: '59 Salish Sea terminals on the map (crude and fuel, refinery docks, bunkering, LNG/LPG, chemical, coal, grain, cement and aggregate, forest products), each with a card: ships that called, emissions, and every source.' },
  { date: '2026-09-28', area: 'Terminal visits', text: '35,942 terminal visits (Jul 2025 – Jun 2026) counted from AIS: a ship stopped within 150–300 m of a berth for 15+ minutes. Tugs at oil and fuel docks are labelled “likely moving a barge”.' },
  { date: '2026-09-28', area: 'Ship tracks', text: 'Detailed Salish Sea tracks now reach 49.6° N and 126.2° W: Vancouver harbour, Burrard Inlet and Indian Arm, the Fraser River, Nanaimo and the Juan de Fuca approach. A new coastline keeps inlets and rivers open to ships.' },
  { date: '2026-09-28', area: 'Ships', text: '1,944 ships added from the larger area, including harbour tugs that never leave Vancouver.' },
  { date: '2026-09-28', area: 'Ship cards', text: 'Scrubber (exhaust gas cleaning) notifications from the IMO’s GISIS database on ship cards.' },
  { date: '2026-09-28', area: 'Terminals', text: '465 IMO-declared port facilities (Canada and US) linked to their terminals. Intalco / Ferndale LPG operator now sourced from Whatcom County (ALA Energy / AltaGas).' },
  { date: '2026-09-28', area: 'Ports', text: 'Official port lists added: Transport Canada, DFO small craft harbours and US Army Corps port areas, with official names on port cards.' },
  { date: '2026-09-28', area: 'Ports', text: '6,006 ports that only Climate TRACE lists are now on the map, with their ship-emission estimates.' },
  { date: '2026-09-28', area: 'Map', text: 'Ship tracks open on Tankers; a picked kind of ship drills down to exact kinds (e.g. oil/chemical tanker, LPG carrier). Larger terminal labels; a tidier left panel.' },
  { date: '2026-09-27', area: 'Ports', text: 'Port card redesign: headline numbers plus Traffic, Ships, Emissions and Trade tabs. Climate TRACE refineries and oil & gas sites added to the Ports layer.' },
]
