/**
 * Public changelog for /ships (earthatlas.org/ships/changelog). Public-facing: plain language, no internal
 * details (environments, bake versions, vendors, costs, unreleased work). Add entries newest first when a
 * change goes live; update COUNTS (with its date) only from verified production numbers.
 */

const S = {
  marinecadastre: { name: 'MarineCadastre AIS', href: 'https://hub.marinecadastre.gov/pages/vesseltraffic' },
  gfw: { name: 'Global Fishing Watch', href: 'https://globalfishingwatch.org' },
  gisis: { name: 'IMO GISIS', href: 'https://gisis.imo.org/Public/' },
  ct: { name: 'Climate TRACE', href: 'https://climatetrace.org' },
  wpi: { name: 'World Port Index', href: 'https://msi.nga.mil/Publications/WPI' },
  bcports: { name: 'BC Ports and Terminals', href: 'https://catalogue.data.gov.bc.ca/dataset/bc-ports-and-terminals' },
  osm: { name: 'OpenStreetMap', href: 'https://www.openstreetmap.org/copyright' },
  gem: { name: 'Global Energy Monitor', href: 'https://globalenergymonitor.org' },
  mep: { name: 'MEP Alliance', href: 'https://www.mepalliance.org/list-of-scrubber-fitted-ships' },
}

export const COUNTS_AS_OF = '2026-10-02'

// { label, value, sources: [S.x | plain string] }
export const COUNTS = [
  { label: 'Ships', value: '41,153', sources: [S.gfw, 'US Coast Guard', 'Transport Canada', 'FCC', S.marinecadastre, 'Wikidata', 'Wikimedia Commons'] },
  { label: 'Ports on the map', value: '9,159', detail: 'World Port Index 2,951 · Climate TRACE 6,006 · GFW 168 · DFO harbours 34', sources: [S.wpi, S.ct, S.gfw, 'Fisheries and Oceans Canada'] },
  { label: 'Terminals', value: '59', detail: '81 berths', sources: [S.bcports, 'US Army Corps of Engineers', 'WA Dept. of Ecology', S.osm, S.gem] },
  { label: 'Terminal visits', value: '37,554', detail: 'at 52 terminals, Jul 2025 – Jun 2026, counted by EarthAtlas from AIS', sources: [S.marinecadastre] },
  { label: 'Port visits', value: '96,465', sources: [S.gfw] },
  { label: 'Ship-port emission estimates', value: '17,907', sources: [S.ct] },
  { label: 'Incidents', value: '9,233', sources: ['US Coast Guard', 'NOAA IncidentNews', 'WA Dept. of Ecology'] },
  { label: 'Ships with scrubber notifications', value: '6,506', detail: '572 matched to EarthAtlas ships', sources: [S.gisis] },
  { label: 'Ships on MEP Alliance scrubber lists', value: '3,845', detail: '3,536 by IMO number + 309 named in voyage reports; 365 matched to EarthAtlas ships', sources: [S.mep] },
  { label: 'Official anchorages', value: '810', sources: [S.marinecadastre, 'eCFR', 'Fisheries and Oceans Canada'] },
  { label: 'Hourly ship-track lines', value: '1,970,155', detail: 'British Columbia + Alaska Jan 2025 – Sep 2026, Salish Sea Jul – Sep 2026', sources: [S.gfw] },
  { label: 'Anchorage stays', value: '15,448', detail: 'by 3,338 vessels at 108 Salish Sea anchorages, Jul 2025 – Jun 2026, counted by EarthAtlas from AIS', sources: [S.marinecadastre] },
  { label: 'IMO port facilities', value: '465', detail: 'Canada and US', sources: [S.gisis] },
]

export const COVERAGE_NOTE = 'Detailed ship tracks cover the Salish Sea for Jul 2025 – Jun 2026; US-wide tracks cover 2015 onward; hourly lines (Global Fishing Watch) cover British Columbia and Alaska from Jan 2025 and the Salish Sea and US West Coast from Jul 2026, updated daily.'

// Newest first. { date, area, text }
export const ENTRIES = [
  // Accuracy figures from the June 2026 check (docs/SHIPS_ACTIVITY_CHECK_2026-06.md, read-only against production 2026-10-06/07);
  // 31 of 112 Salish anchorages contain no 0.01° grid point (activity_inputs.json, production polygons).
  { date: '2026-10-07', area: 'Terminals · Anchorages · Search', text: 'Terminal and anchorage activity now continues past NOAA’s latest month. NOAA’s per-minute AIS, which counts visits berth by berth, is published about three months late (it runs through June 2026); for the months after that, terminal visits and anchorage stays are now estimated from hourly ship positions (Powered by Global Fishing Watch), marked ≈ and linked to their own record, and replaced by NOAA’s counts as NOAA publishes each month, which now loads by itself. Hourly positions sit on a grid about 1 km across, so neighbouring terminals closer than that can’t be told apart: at the Anacortes refineries, Westridge and Shellburn, the Tacoma oil docks and Seattle’s Harbor Island the card shows a range (for example ≈0–12 visits: none can only be this terminal, 12 could be this one or its neighbour) and names the neighbour. Tug visits are not counted from hourly positions (tugs moor right beside the terminals they serve). Checked against NOAA’s June 2026 counts in the Salish Sea: 90% of cargo-ship and tanker visits found, and 90% of visits credited to one terminal were at that terminal. Anchorages now open a card like the terminals’ (Ships and About tabs, its own link) instead of a small popup; 31 of the 112 Salish Sea anchorages are smaller than the grid and say so instead of showing zero. With one or two months picked, the charts on both cards show each day. And the “Fly to a place” search now finds the ports, terminals, anchorages and facilities /ships tracks, by name or another name (Vendovi South is also found as “Anacortes”), and opens their card.' },
  // Numbers verified against production 2026-10-07 (read-only counts after prod.sh import-facilities): 27 facilities at 26 WA
  // terminals, 272 permits (13 WA-PARIS state-only), 4,339 documents, 2,353 violations, 204 SEPA reviews, 6 dock citations.
  { date: '2026-10-07', area: 'Terminals · Permits', text: 'Permits now cover every Washington terminal on the map: all 26, from the Cherry Point and Anacortes refineries to the Tacoma tideflats terminals, the Harbor Island fuel terminals, Tacoma LNG, the grain, cement and scrap-metal docks, two Navy fuel piers and Port Angeles. Each terminal’s Permits tab names the facility behind the dock (27 in all) and lists its permits and program records from EPA and Washington Ecology (272, including 13 state-only permits EPA doesn’t track), with 4,339 documents linked to the agencies’ copies, 2,353 recorded violations, enforcement actions and inspection reports, and 204 environmental (SEPA) reviews of their projects. Where a facility has no record of a kind (for example no SEPA review on file), the tab says so.' },
  // Numbers verified against production 2026-10-06 (read-only counts after prod.sh import-facilities): 3 facilities, 59 permits
  // (2 WA-PARIS state-only), 1,274 documents, 96 SEPA reviews, 358 violations, 5 permit↔dock coverage citations.
  { date: '2026-10-06', area: 'Terminals · Permits', text: 'Terminal cards now have a Permits tab, starting with three Salish Sea facilities: the BP Cherry Point refinery, the Marathon Anacortes refinery, and Tesoro Logistics, which owns the Marathon refinery’s wharf. It lists every permit and program record EPA and Washington Ecology hold for the facility behind the dock (59 in all, including 2 state-only permits EPA doesn’t track), and says plainly that these are the facility’s permits, not the dock’s; a permit is marked “covers this dock” only where its own text names the dock, quoted with the page (5 so far). Click a permit to open its own page: who issued it, its versions and dates, and tabs for its documents (1,274 in all, linked to the agency’s copies: permits, fact sheets, inspection reports, penalty notices and orders), its enforcement actions and inspections (each linked to the agency’s letter, order or EPA case report where one exists, with Ecology’s decision and the violations behind it), its violations (358, with the measured value, the limit and the outfall), and the environmental (SEPA) reviews of the facility’s projects (96, from Washington Ecology’s SEPA Register). Terminal cards also gain “Show on map”.' },
  // Numbers from the published hourly-line month manifests 2026-10-06 (Jul 480,118 lines / 17,632 ships; Aug 483,657 / 17,797;
  // Sep 320,841 / 15,510).
  { date: '2026-10-06', area: 'Ship tracks · Ship cards', text: 'The hourly ship-track lines (Powered by Global Fishing Watch) now cover the US West Coast, from the Salish Sea south to San Diego, from July 2026 on, updated daily about four days behind. With them, July–September 2026 now hold 480,118, 483,657 and 320,841 lines from 17,632, 17,797 and 15,510 ships. Where NOAA’s per-minute AIS exists (through June 2026) its tracks are still the ones shown, and NOAA replaces the hourly lines when it publishes a newer month. Also fixed: clicking an hourly line of a ship that EarthAtlas had just looked up could still say “Not yet in EarthAtlas’s ship records” for a minute or so; the ship card now opens right away.' },
  { date: '2026-10-02', area: 'Ship cards · Ship tracks', text: 'Hover over a picked ship’s own tracks to see where it was: a top-down ship icon sits on the line pointing the way it was heading, drawn by kind of ship (tanker, cargo, cruise ship, ferry, fishing boat, tug, sailboat) and sized by its length, with its name, kind of ship, the local time there, its speed and its heading. On NOAA tracks and on estimated (dashed) paths the time is spread along the line from its start and end (marked ≈) and the speed is the average for the line. Ship cards also gain “View in” links to the ship’s public page on MarineTraffic (by IMO number), VesselFinder and MyShipTracking (by MMSI).' },
  { date: '2026-10-02', area: 'Ship records', text: 'Every ship seen in the hourly ship-track lines (British Columbia, Alaska and the Salish Sea since July 2026) is being added to EarthAtlas’s ship records with what it broadcast: name, MMSI, call sign, IMO number and flag (AIS, as served by Global Fishing Watch), and Global Fishing Watch’s vessel type, each with the first and last time it was seen. Ships we already held are linked by their IMO number, or by MMSI plus the same name or call sign; an MMSI alone never merges two ships. So clicking one of these lines now opens a ship card, filled in as far as the data goes. Records are added for each completed month.' },
  { date: '2026-10-02', area: 'Ship tracks', text: 'The hourly ship-track lines for British Columbia and Alaska are being re-drawn against the full coastline: some lines cut straight across islands and headlands (for example Digby and Kaien Islands at Prince Rupert) because part of the coastline was missing when they were drawn. Clicking an hourly line of a ship that is not yet in our ship records now shows the name, flag and IMO number the ship broadcast (AIS), as served by Global Fishing Watch, instead of only “no identity record”.' },
  // Numbers from the published GFW index 2026-10-02 (21 months, 1,970,155 lines; ships per month 1,647–12,206).
  { date: '2026-10-02', area: 'Ship tracks', text: 'Ship tracks now reach British Columbia and all of Alaska, and the Salish Sea no longer stops at NOAA’s latest month. Where NOAA has no per-minute AIS, the lines come from hourly ship positions (Powered by Global Fishing Watch), so they are straighter than NOAA’s; where a straight line between two hours would cross land, EarthAtlas estimates the path along the water from official coastlines (OpenStreetMap, Alaska DNR, Natural Resources Canada), keeping off tidal flats and marshes and following the lanes ships actually use, and draws it dashed. Each line is typed from EarthAtlas’s own ship records where we know the ship, so the Kind of ship filters work on them (the Valdez tanker route now shows under Tanker). Jan 2025 – Sep 2026 for British Columbia and Alaska, and Jul – Sep 2026 for the Salish Sea: 1,970,155 lines, from 1,647 ships in December 2025 to 12,206 in August 2026. Updated daily, about four days behind. When NOAA publishes a month, its tracks replace the hourly ones there.' },
  { date: '2026-10-02', area: 'Ship tracks', text: 'The numbers on the Ship tracks filters (the “Narrow to” kinds, such as Oil tanker, and Scrubber-fitted) now count the ships whose tracks are on the map right now, for the months and filters you have picked, and they update as you move the map. Each number is what that filter will draw: turn it on and exactly that many ships’ lines remain. Each ship counts once, however many trips it made. The note under Scrubber-fitted also gives the total on record.' },
  { date: '2026-09-30', area: 'Sharing', text: 'A link to a particular /ships map view now previews with a picture of that view (where the map is, and which layers are on). Links to earthatlas.org/ships itself now preview with their own picture, “The open record of every ship”, instead of the general EarthAtlas card, and the page’s title and description now read “Ships — the open record of every ship”: where it’s sailed, what it’s burned, and the impact it may leave behind.' },
  // Numbers below verified against production 2026-09-30 (read-only counts after the anchorage and MEP imports):
  // 15,448 stays / 3,338 vessels / 108 anchorages; Vendovi South 87 stays by 51 ships; MEP 334 by IMO, 31 + 32 by name;
  // scrubber filter 594 ships (IMO 460, MEP 365, both 231).
  { date: '2026-09-30', area: 'Ship cards', text: 'Clearer ship cards. A ship’s scrubber (exhaust gas cleaning system) now has its own highlighted block near the top of the Overview, with the official IMO filing and the MEP Alliance reports each on their own line and linked to their source. The owner and operator now sit right under the ship’s name. When no source has emissions for a ship, the Emissions tab now says so in one line. The History tab is now the last tab.' },
  { date: '2026-09-30', area: 'Ship cards · Ship tracks', text: 'Ship cards now also show when a ship is on the MEP Alliance scrubber lists, beside (never merged with) the scrubber filings flag states make to IMO: the list, the date reported, and the owner and charterer the list names, each linked to its source. These are reported facts from an advocacy group, not registry records, and are labelled that way. MEP Alliance lists 3,536 scrubber-fitted (or pending) bulk carriers, tankers, container ships and cruise ships by IMO number, 334 of them ships we hold, and 492 reported voyages of 309 named ships. That voyage list gives no IMO number, so EarthAtlas matched 63 of those ships by name: 31 confirmed by a second fact, and 32 marked “matched by name (inferred)” because they are the only large ship of that name seen in the Salish Sea. New “Scrubber-fitted” filter under Ship tracks shows only the tracks of the 594 ships with a scrubber filed with IMO (460) or on the MEP Alliance lists (365; 231 are on both).' },
  { date: '2026-09-30', area: 'Anchorages', text: 'Official anchorage areas are now on the map (inside Ports & terminals, from zoom 8): 33 CFR anchorages in US waters, Fisheries and Oceans Canada’s active commercial anchorages in BC, and the Puget Sound anchorages the Coast Guard’s traffic service uses without a legal designation (clearly marked). Click an anchorage’s name for who anchors there: EarthAtlas counted every stay from AIS (a ship stopped, under 0.5 knots, inside the area for an hour or more) with the number of ships, ship-hours, the kinds of ship and the ships that spent the most days there, each linked to the count’s record. 15,448 stays by 3,338 vessels at 108 Salish Sea anchorages, Jul 2025 – Jun 2026. Vendovi South (off Vendovi Island): 87 stays by 51 ships, 36 of them tankers (SILVER LONDON 14 days, ALTHEA 13, HIGH SEAS 11). Pleasure boats and other small craft are counted too and shown apart by kind. Anchorages now also show other names they go by, each with its source: Vendovi South is “Vendovi Island South (VIS)” to the Coast Guard’s Puget Sound traffic service (its user’s manual) and Vendovi East is “Vendovi Island East (VIE)”; Global Fishing Watch files Vendovi South under “Anacortes”, so port visits there read Anacortes. Anchorages outside the area our AIS covers say so instead of showing zero.' },
  { date: '2026-09-29', area: 'Ship cards', text: 'The Emissions tab now shows a ship’s verified EU MRV emissions reports above Climate TRACE’s modelled estimates, as two separate blocks labelled “verified” and “estimate”; the two are never added together. 1,767 of our ships have at least one report (2018–2025), 1,652 of them seen in the Salish Sea. The newest year shows CO₂ (from 2024 also methane, nitrous oxide and CO₂-equivalent), CO₂ at berth, fuel burned, hours at sea, CO₂ per nautical mile, the ship’s design efficiency rating and who verified the report; earlier years get one line each. Every figure links to the European Maritime Safety Agency’s page for that ship and year. These reports cover only voyages to, from and between EU/EEA ports and time at berth there, so for ships trading mostly in the Pacific they are far below the ship’s whole-year emissions (EURODAM: 298 t CO₂ in 2024).' },
  // Numbers below verified against production 2026-09-29 (tc4 import + readTerminalCard on the prod DB):
  // 37,554 visits at 52 terminals; BP Cherry Point 1,122; HF Sinclair 1,039.
  { date: '2026-09-29', area: 'Terminals', text: 'Official berth facts on terminal cards (About tab), each linked to its document: berth names, lengths and depths from the Pacific Pilotage Authority’s berth list (November 2025) and the Port of Vancouver’s berth soundings sheets, for Vancouver Wharves (Berths 1, 2/3, 4 and 5), Richardson International (one berth) and Pacific Terminal (Pacific Elevator 4). Where BC’s terminal list disagrees (it gives Richardson 108 m; the pilotage list 183 m, the port sheet 164 m), both are shown. The newer document now sets how close a stopped ship must be to count: Vancouver Wharves Berth 1 (231 m) within 166 m instead of 150 m; Pacific Terminal’s berth (270 m between mooring dolphins, not 305 m) within 185 m instead of 203 m. Ships counted at these three terminals are unchanged; 20 more other vessels are listed at Vancouver Wharves and 18 fewer at Pacific Terminal. 37,554 terminal visits in all, Jul 2025 – Jun 2026.' },
  { date: '2026-09-29', area: 'Terminal visits', text: 'Chemical tankers now count as visits at refinery docks and crude and fuel-product terminals, the same rule the Climate TRACE port stays already use (many product tankers, which load refined fuel at these docks, are listed as chemical tankers). 7 more visits, Jul 2025 – Jun 2026: BP Cherry Point 1,122 (was 1,120), HF Sinclair Puget Sound 1,039 (was 1,034); other oil docks unchanged.' },
  { date: '2026-09-29', area: 'Terminals', text: 'Terminal cards’ Emissions tab now shows Climate TRACE’s estimate for ships while they are stopped at the terminal’s own berths (port stays): 7,262 stays by 2,092 ships of the kinds each terminal serves, at 46 of the 59 terminals, 2024–2025, about 262,000 t CO₂e. Chemical tankers count at refinery and oil docks. Stays by other kinds of ship at the same spot are listed apart, not added in; stays that could belong to two neighbouring terminals are left out.' },
  { date: '2026-09-29', area: 'Ship cards', text: 'The Emissions tab now says who tracked the ship for Climate TRACE: OceanMind (large ships) or Global Fishing Watch (smaller ships), and shows the ship’s deadweight and Climate TRACE’s modelled CO₂ per nautical mile for the 4,379 ships OceanMind tracks. Voyage and port-stay figures updated to Climate TRACE’s latest release and extended north to Vancouver harbour, Roberts Bank, Howe Sound and Nanaimo: 15,817 Climate TRACE ship entries with trips or stays that began in 2024–2025.' },
  { date: '2026-09-28', area: 'Terminals', text: 'Berths estimated from where ships actually stop, for Richardson and Vancouver Wharves (North Vancouver), whose one listed point missed the berths ships use. Each estimate is labelled as such on the terminal card, with how many ships and stops it rests on. Richardson now shows 42 visits by 24 bulk carriers (it showed none), plus 180 visits by cargo ships whose exact kind isn’t stated; Vancouver Wharves 64 visits by 53 ships, up from 25.' },
  { date: '2026-09-28', area: 'Terminals', text: 'Real berth positions for 8 multi-berth terminals (Westshore, Neptune, Westridge, Alliance Grain, Cargill, BP Cherry Point, Crofton, Pacific Coast Terminals), so ships at every berth are counted. Westshore now shows 62 visits by 52 bulk carriers.' },
  { date: '2026-09-28', area: 'Terminals', text: '59 Salish Sea terminals on the map (crude and fuel, refinery docks, bunkering, LNG/LPG, chemical, coal, grain, cement and aggregate, forest products), each with a card: ships that called, emissions, and every source.' },
  { date: '2026-09-28', area: 'Terminal visits', text: '35,942 terminal visits (Jul 2025 – Jun 2026) counted from AIS: a ship stopped within 150–300 m of a berth for 15+ minutes. Tugs at oil and fuel docks are labelled “likely moving a barge”.' },
  { date: '2026-09-28', area: 'Ship tracks', text: 'Detailed Salish Sea tracks now reach 49.6° N and 126.2° W: Vancouver harbour, Burrard Inlet and Indian Arm, the Fraser River, Nanaimo and the Juan de Fuca approach. A new coastline keeps inlets and rivers open to ships.' },
  { date: '2026-09-28', area: 'Ships', text: '1,944 ships added from the larger area, including harbour tugs that never leave Vancouver.' },
  { date: '2026-09-28', area: 'Ship cards', text: 'Scrubber (exhaust gas cleaning) notifications from the IMO’s GISIS database on ship cards.' },
  { date: '2026-09-28', area: 'Terminals', text: '465 IMO-declared port facilities (Canada and US) linked to their terminals. Intalco / Ferndale LPG operator now sourced from Whatcom County (ALA Energy / AltaGas).' },
  { date: '2026-09-28', area: 'Ports', text: 'Official port lists added: Transport Canada, DFO small craft harbours and US Army Corps port areas, with official names on port cards.' },
  { date: '2026-09-28', area: 'Ports', text: '6,006 ports that only Climate TRACE lists are now on the map, with their ship-emission estimates.' },
  { date: '2026-09-28', area: 'Map', text: 'Ship tracks open on Tankers; a picked kind of ship drills down to exact kinds (e.g. oil/chemical tanker, LPG carrier). Larger terminal labels; a tidier left panel.' },
  { date: '2026-09-27', area: 'Ports', text: 'Port card redesign: headline numbers plus Traffic, Ships, Emissions and Trade tabs. Climate TRACE refineries and oil & gas sites added to the Ports layer.' },
]
