/**
 * BirdCast observed nocturnal bird migration — shared fetch/decode/regrid core.
 * Source catalog, caveats and the required citation: docs/BIRDCAST_DATA.md.
 *
 * Upstream (Cornell Lab of Ornithology) publishes every 10-minute radar
 * mosaic as a Zarr v2 web-mercator pyramid in a public S3 bucket:
 *   zarr/YYYY/MM/DD/raster_<YYYYMMDDHHmm>.zarr/<level>/values/<chunk>
 * float32 [band, y, x], bands = mtr (birds/km/h), vid, u, v (m/s), 128 px
 * chunks, zlib. We read level 3 (1024² global, ≈30 km at 40°N — the native
 * cell size); CONUS sits entirely inside four chunks. The bucket sends no
 * CORS headers, so the browser can't read it — hence this bake.
 *
 * Frames are resampled (bilinear, no-data aware) from mercator onto a regular
 * 0.25° lat/lon box so they ride the existing grid/tape machinery unchanged.
 * Nothing is modelled, smoothed or gap-filled: a cell with no upstream value
 * stays missing.
 *
 * Upstream fills its whole bounding rectangle — far from any radar (open
 * Pacific, deep Mexico/Canada) the values are interpolation relaxing to a
 * constant (≈313 birds/km/h on 2026-09-20), not observations. We keep the
 * contiguous U.S. expanded by 100 miles (api/_birdcast-conus-mask.js,
 * generated by scripts/bake-birdcast/make-conus-mask.mjs): the Great Lakes and
 * the offshore strip coastal radars see, not the far field.
 */

import zlib from 'node:zlib'
import { existsSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CONUS_MASK_B64, CONUS_MASK_DIMS } from './_birdcast-conus-mask.js'

export const BIRDCAST_BUCKET = 'https://is-birdcast-observed-prod.s3.us-east-1.amazonaws.com'
export const BIRDCAST_SOURCE_NAME = 'BirdCast, Cornell Lab of Ornithology'
export const BIRDCAST_SOURCE_URL = 'https://birdcast.org/migration-tools/live-migration-maps'

const LEVEL = 3
const CHUNK = 128
const CHUNK_ROWS = [2, 3]
const CHUNK_COLS = [1, 2]
const WORLD = 20037508.342789244
const PX = (2 * WORLD) / (CHUNK * 2 ** LEVEL) // metres per level-3 pixel
const R = 6378137
const BANDS = { mtr: 0, vid: 1, u: 2, v: 3 }

// Output box: 24.5–49.5°N, 125–66.75°W at 0.25° (lon in 0–360 like the other bakes).
const STEP = 0.25
export const BIRDCAST_LAT = Array.from({ length: 101 }, (_, i) => 24.5 + i * STEP)
export const BIRDCAST_LON = Array.from({ length: 234 }, (_, i) => 235 + i * STEP)

// scripts/bake-birdcast/fetch-zarr.mjs keeps an untouched local copy of the
// chunks; when it's there (a dev machine doing a backfill) read it instead of
// asking Cornell's bucket again. Never present on Vercel.
const LOCAL_CACHE = join(dirname(fileURLToPath(import.meta.url)), '..', 'scripts', 'bake-birdcast', 'raw', `zarr-l${LEVEL}`)

export const birdcastStamp = (ms) => new Date(ms).toISOString().replace(/[-:T]/g, '').slice(0, 12)

async function readChunk(ms, name) {
  const s = birdcastStamp(ms)
  const local = join(LOCAL_CACHE, s.slice(0, 4), s.slice(4, 6), s.slice(6, 8), s, name)
  if (existsSync(local)) return readFileSync(local)
  const url = `${BIRDCAST_BUCKET}/zarr/${s.slice(0, 4)}/${s.slice(4, 6)}/${s.slice(6, 8)}/raster_${s}.zarr/${LEVEL}/values/${name}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`birdcast ${s} chunk ${name}: HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

const CONUS_BITS = Buffer.from(CONUS_MASK_B64, 'base64')
const inConus = (i) => (CONUS_BITS[i >> 3] >> (i & 7)) & 1

const frameCache = new Map() // valid_ms → Promise<frame>; the three tapes of one bake share a decode

/**
 * One upstream frame → { valid_ms, mtr, vid, u, v } as Float32Arrays on the
 * BIRDCAST_LAT × BIRDCAST_LON grid (row-major from lat0; NaN = no upstream value).
 */
export function fetchBirdcastFrame(valid_ms) {
  if (!frameCache.has(valid_ms)) {
    frameCache.set(valid_ms, loadFrame(valid_ms).catch((err) => { frameCache.delete(valid_ms); throw err }))
    if (frameCache.size > 60) frameCache.delete(frameCache.keys().next().value)
  }
  return frameCache.get(valid_ms)
}

async function loadFrame(valid_ms) {
  // Mosaic the four chunks into one [band][row][col] window of the level-3 grid.
  const W = CHUNK * CHUNK_COLS.length
  const Hh = CHUNK * CHUNK_ROWS.length
  const win = Object.keys(BANDS).map(() => new Float32Array(W * Hh))
  for (let cr = 0; cr < CHUNK_ROWS.length; cr++) {
    for (let cc = 0; cc < CHUNK_COLS.length; cc++) {
      const raw = zlib.inflateSync(await readChunk(valid_ms, `0.${CHUNK_ROWS[cr]}.${CHUNK_COLS[cc]}`))
      if (raw.length !== 4 * CHUNK * CHUNK * 4) throw new Error(`birdcast ${birdcastStamp(valid_ms)}: unexpected chunk size ${raw.length}`)
      const f = new Float32Array(raw.buffer, raw.byteOffset, raw.length / 4)
      for (let b = 0; b < 4; b++) {
        for (let y = 0; y < CHUNK; y++) {
          win[b].set(f.subarray((b * CHUNK + y) * CHUNK, (b * CHUNK + y + 1) * CHUNK), (cr * CHUNK + y) * W + cc * CHUNK)
        }
      }
    }
  }
  // Upstream marks no-data two ways (zarr fill 9.97e36 and −3.4e38).
  const ok = (v) => Math.abs(v) < 1e30
  const col0 = CHUNK_COLS[0] * CHUNK
  const row0 = CHUNK_ROWS[0] * CHUNK
  const nLat = BIRDCAST_LAT.length
  const nLon = BIRDCAST_LON.length
  if (CONUS_MASK_DIMS[0] !== nLat || CONUS_MASK_DIMS[1] !== nLon) throw new Error('birdcast: CONUS mask does not match the bake grid — re-run make-conus-mask.mjs')
  const out = Object.fromEntries(Object.keys(BANDS).map((k) => [k, new Float32Array(nLat * nLon).fill(NaN)]))
  let valid = 0
  for (let r = 0; r < nLat; r++) {
    const latRad = (BIRDCAST_LAT[r] * Math.PI) / 180
    const my = R * Math.log(Math.tan(Math.PI / 4 + latRad / 2))
    const fy = (WORLD - my) / PX - 0.5 - row0
    const y0 = Math.floor(fy)
    const wy = fy - y0
    if (y0 < 0 || y0 >= Hh - 1) continue
    for (let c = 0; c < nLon; c++) {
      const mx = (R * (BIRDCAST_LON[c] - 360) * Math.PI) / 180
      const fx = (mx + WORLD) / PX - 0.5 - col0
      const x0 = Math.floor(fx)
      const wx = fx - x0
      if (x0 < 0 || x0 >= W - 1) continue
      if (!inConus(r * nLon + c)) continue
      const idx = [y0 * W + x0, y0 * W + x0 + 1, (y0 + 1) * W + x0, (y0 + 1) * W + x0 + 1]
      const wts = [(1 - wx) * (1 - wy), wx * (1 - wy), (1 - wx) * wy, wx * wy]
      // Validity is decided on mtr; a cell needs most of its footprint present.
      let wsum = 0
      for (let k = 0; k < 4; k++) if (ok(win[0][idx[k]])) wsum += wts[k]
      if (wsum < 0.5) continue
      for (const [name, b] of Object.entries(BANDS)) {
        let s = 0
        for (let k = 0; k < 4; k++) if (ok(win[0][idx[k]])) s += win[b][idx[k]] * wts[k]
        out[name][r * nLon + c] = s / wsum
      }
      valid++
    }
  }
  if (valid < nLat * nLon * 0.25) throw new Error(`birdcast ${birdcastStamp(valid_ms)}: only ${valid} valid cells`)
  return { valid_ms, ...out }
}

/** Newest on-the-hour frame upstream has published (they run ≈15 min behind). */
export async function latestBirdcastHour(now = Date.now()) {
  for (let back = 0; back < 6; back++) {
    const t = Math.floor((now - 20 * 60000) / 3.6e6) * 3.6e6 - back * 3.6e6
    try { await fetchBirdcastFrame(t); return t } catch { /* not published yet / gap — try the hour before */ }
  }
  throw new Error('birdcast: no frame in the last 6 hours')
}
